# Generated by Django 2.0.6 on 2018-06-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='client',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='relationships',
            old_name='client',
            new_name='student',
        ),
    ]
