# Generated by Django 2.0.6 on 2018-07-22 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20180624_2301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Lesson',
        ),
    ]
