# Generated by Django 2.0.6 on 2018-07-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180722_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(default='2018-01-01 12:12', null=True),
        ),
    ]
