# Generated by Django 2.0.6 on 2018-07-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_lesson_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
    ]
