# Generated by Django 2.0.3 on 2018-03-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20180310_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
