# Generated by Django 2.0.3 on 2018-03-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_events_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_time',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.CharField(max_length=32),
        ),
    ]
