# Generated by Django 2.0.3 on 2018-03-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_profile_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(blank=True, default='{}', max_length=1000, null=True),
        ),
    ]
