# Generated by Django 2.0.6 on 2018-06-26 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('full_name', models.CharField(max_length=24)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('user_type', models.CharField(max_length=16)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availability', models.CharField(blank=True, default='{}', max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
