# Generated by Django 2.0.6 on 2018-06-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_signed_up',
            field=models.BooleanField(default=False),
        ),
    ]
