# Generated by Django 2.0.6 on 2018-07-28 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='availability',
        ),
        migrations.AddField(
            model_name='availability',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
