# Generated by Django 2.0.6 on 2018-07-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180728_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.CharField(max_length=15),
        ),
    ]
