# Generated by Django 2.0.6 on 2018-08-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180730_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day',
        ),
    ]
