# Generated by Django 2.0.6 on 2018-08-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_availability_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='day',
            field=models.CharField(default='pew', max_length=15),
            preserve_default=False,
        ),
    ]
