# Generated by Django 2.0.6 on 2018-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_availability_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
