# Generated by Django 2.0.6 on 2018-11-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='picture',
            field=models.ImageField(blank=True, upload_to='notification_pictures'),
        ),
    ]
