# Generated by Django 2.0.6 on 2018-11-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_notification_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
