# Generated by Django 2.0.6 on 2018-11-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20181109_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='link_one',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link_three',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link_two',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
