# Generated by Django 2.0.6 on 2019-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190218_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_tutorial',
            field=models.BooleanField(default=True),
        ),
    ]
