# Generated by Django 2.0.6 on 2019-07-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
