# Generated by Django 2.0.6 on 2019-09-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20190827_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day',
        ),
        migrations.AddField(
            model_name='availability',
            name='repeat_weekly',
            field=models.BooleanField(default=False),
        ),
    ]
